config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, skip: [:password, :confirm], controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
  }

  # devise_for :users, skip: [:password, :confirm]


 patch 'wastes/count_up' => 'wastes#count_up'
 patch 'wastes/count_down' => 'wastes#count_down'
 patch 'wants/purchase' => 'wants#purchase'

# resources :users, :except => :show do
resources :users, only:[:index, :update, :edit, :achievement, :mypage, :follows, :followers, :hide, :search] do
  get :search, on: :collection
  resource :relationships, only: [:create, :destroy]
  get :follows
  get :followers
end


put 'users/:id/hide' => 'users#hide', as:'users_hide'
put 'wastes/:id/hide' => 'wastes#hide', as:'wastes_hide'
put 'wastes/:id/reveal' => 'wastes#reveal', as:'wastes_reveal'
put 'wastes/:id/hide_away' => 'wastes#hide_away', as:'wastes_hide_away'
put 'wants/:id/hide' => 'wants#hide', as:'wants_hide'
put 'wants/:id/reveal' => 'wants#reveal', as:'wants_reveal'

resources :wastes, only:[:index, :create, :count_up, :count_down, :update, :hide, :reveal, :hide_away]
resources :wants, only:[:index, :show, :create, :purchase, :update, :destroy, :hide, :reveal] do
  resource :cheers, only:[:create, :destroy]
end


root 'homes#top'
get 'homes/about'
get 'mypage' => 'users#mypage'
get 'achievement' => 'users#achievement'


end

app/models/want.rb
class Want < ApplicationRecord
  belongs_to :user
  has_many :cheers, dependent: :destroy
  validates :name, presence: true, length: {maximum: 15}
  validates :price, numericality: { only_integer: true }
  validates :reason, length: {maximum: 15}
  attachment :want_image, content_type: ["image/jpeg", "image/png"]

  def cheered_by?(user)
    cheers.where(user_id: user.id).exists?
  end
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @want = Want.new
    @wants = current_user.wants.all
    # @wants = Want.all
  end

  def show
    @want = Want.find(params[:id])
  end

  def create
    @want = Want.new(want_params)
    @wants = current_user.wants.all
    @want.user_id = current_user.id
    if @want.save
# 非同期の時
      if request.xhr?
        @row_number = params[:want][:row_number]
        render status: :created
      else
        redirect_to wants_path
      end

    else
      @want.want_image = nil
      @user = current_user
      render 'index'
    end
  end


  def purchase # 目標達成／購入のページ用
    @user = current_user
    @want = Want.find(params[:want_id])
    @user.purchase_price = @user.purchase_price + @want.price
    @user.save
    redirect_to achievement_path
  end

  def update
    @want = Want.find(params[:id])
    if @want.update(want_params)
      redirect_to wants_path
    else
      @user = current_user
      render 'index'
    end
  end

  def destroy
    want = Want.find(params[:id])
    want.destroy
    flash[:destroy] = "削除しました"
    redirect_to wants_path
  end

# ↓全体表示させるかさせないか、のメソッド
  def hide
    @want = Want.find(params[:id])
    @want.update(status: 1)
  end

  def reveal
    @want = Want.find(params[:id])
    @want.update(status: 0)
  end



  private
  def want_params
    params.require(:want).permit(:name, :price, :reason, :want_image, :want_image_id)
  end
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/wants/_cheer.html.erb
<!-- 応援ボタン cheer -->
<% if want.cheered_by?(current_user) %>
  <%= link_to want_cheers_path(want), method: :delete, remote: true do %>
<i class="fa fa-child" aria-hidden="true" style="color:red;"></i>
      <%= want.cheers.count %>人が応援中
  <% end %>
<% else %>
  <%= link_to want_cheers_path(want), method: :post, remote: true do %>
<i class="fa fa-child" style="color:lightgray"></i>
    <%= want.cheers.count %>人が応援中
  <% end %>
<% end %>

app/views/wants/_hide.html.erb
<!-- 全体表示させるかどうかのボタン -->
<% if want.status == 0 %>
  <%= link_to "しない", wants_hide_path(want), method: :put,remote: true, class: "btn btn-danger" %>
<% else %>
  <%= link_to "する", wants_reveal_path(want), method: :put,remote: true, class: "btn btn-success" %>
<% end %>

app/views/wants/create.js.erb
// $(document).ready ->
  // $(document).on("ajax:success", (event) ->
  //   [data, status, xhr] = event.detail
  //   $("btn_<%= @row_number %>").append xhr.responseText
  // ).on "ajax:error", (event) ->
  //   $("#new_article").append "<p>ERROR</p>"


  // var forms = document.querySelectorAll(".window_btn")
  // var form = document.querySelector(".window_btn")
  // // forms.forEach(form => {
  //   form.addEventListener('ajax:success', function(event) {
  //     alert("追加しました！");
  //   })
  // })


  var el = document.getElementById("btn_<%= @row_number %>")
  el.addEventListener('ajax:success', function(event) {
    var btn = document.querySelector("#btn_<%= @row_number %> input[type='submit']")
    btn.removeAttribute("data-disable-with")
    btn.value = '追加完了！'

})

app/views/wants/hide.js.erb
$('#hide_<%= @want.id %>').html("<%= j(render partial: 'wants/hide', locals:{want: @want}) %>");

app/views/wants/index.html.erb
<div class="container">
  <div class="table-heading">
    <h2>目標一覧／変更する</h2>
    <h4>(変更修正：四角の中の文字を修正して更新ボタンを押す)</h4>
  </div>
  <div class="index-base">
    <div class="row">

      <!-- 欲しいもの一覧表示 -->
      <div class="table-border table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th class="col-xs-2">イメージ</th>
              <th class="col-xs-2">欲しいもの</th>
              <th class="col-xs-2">金額(円)</th>
              <th class="col-xs-3">理由</th>
              <th class="col-xs-1">更新</th>
              <% if flash[:destroy] %>
              <th class="col-xs-1 alert">
                <%= flash[:destroy] %>
              </th>
              <% else %>
              <th class="col-xs-1">削除</th>
              <% end %>
              <th class="col-xs-1">全体公開</th>
            </tr>
          </thead>
          <tbody>
            <% @wants.each_with_index do |want, i| %>
            <%= form_with model: want, local: true do |f| %>

            <tr>
              <td>
                <%= f.file_field :want_image, class: "img_field", id: "img_field_#{i}", style: "display:none;" %>
                <%= attachment_image_tag want, :want_image, :fill, 80, 80, fallback: "want_no_image.jpg", size:'80x80', onClick: "$('#img_field_#{i}').click()", class: "center-block img-thumbnail img-responsive img_prev" %>
              </td>
              <td><%= f.text_field :name %></td>
              <td><%= f.text_field :price %></td>
              <td><%= f.text_field :reason %></td>
              <td><%= f.submit "←更新", class: "btn btn-success" %></td>
              <td><%= link_to "削除", want_path(want), method: :delete, class: "btn btn-danger" %></td>
              <td>
                <div id="hide_<%= want.id %>">
                  <%= render partial: 'wants/hide', locals:{ want: want } %>
                </div>
              </td>
            </tr>
          </tbody>
          <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>

  <!-- 欲しいもの追加 -->
  <h2>欲しいものを追加する</h2>
  <div class="index-base">
    <div class="row">
      <div class="table-border table-responsive">
        <%= form_with model: @want, local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <table class="table">
          <thead>
            <tr>
              <th class="col-xs-2">画像追加</th>
              <th class="col-xs-3">欲しいもの</th>
              <th class="col-xs-2">金額(円)</th>
              <th class="col-xs-4">理由</th>
              <th class="col-xs-1">追加</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <label><%= f.file_field :want_image, class: "img_field", style: "display:none;", accept: 'image/jpg, image/jpeg, image/png' %>
                  <%= attachment_image_tag @want, :want_image, fallback: "want_no_image.jpg", size:'80x80', onClick: "$('#img_field').click()", class: "center-block img-thumbnail img-responsive img_prev" %></label>
                </td>
                <td><%= f.text_field :name %></td>
                <td><%= f.text_field :price %></td>
                <td><%= f.text_field :reason %></td>
                <td><%= f.submit "←追加", class: "btn btn-success" %></td>
              </tr>
            </tbody>
          </table>
          <% end %>
        </div>
      </div>
    </div>

    <!-- 遷移ボタン -->
    <div class="row row-btn">
      <div class="index-btn">
        <%= link_to "マイページ", mypage_path, class: "btn btn-default" %>
        <%= link_to "無駄遣いを入力／変更する", wastes_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
<script>
  $(document).ready( function() {
    $('.img_field').attr('src', `<%= asset_path('want_no_image.jpg') %>`)
  })
</script>

app/views/wants/reveal.js.erb
$('#hide_<%= @want.id %>').html("<%= j(render partial: 'wants/hide', locals:{want: @want}) %>");

app/views/wants/show.html.erb
<!-- 購入ボタンを押した遷移先 -->
<div class="container">
  <div class="want-base">
  <div class="row">
      <div class="col-xs-6">
        <%= attachment_image_tag @want, :want_image, :fill, 60, 60, fallback: "want_no_image.jpg", size:'150x150' %>
        <br>
        <%= @want.name %>
      </div>
      <div class="col-xs-6">
      <div class="want-info">
        購入金額<br>
        <%= @want.price.to_s(:delimited) %>円<br>
        <%= @want.reason %><br>
        登録日<br><%= @want.created_at.strftime("%Y年%m月%d日") %>
      </div>
      </div>
      <%= button_to "購入する", {controller: 'wants', action: 'purchase'}, {method: :patch, :class => "btn btn-success",  params: {want_id: @want.id}} %>
    </div>
  </div>
</div>