config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, skip: [:password, :confirm], controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
  }

  # devise_for :users, skip: [:password, :confirm]


 patch 'wastes/count_up' => 'wastes#count_up'
 patch 'wastes/count_down' => 'wastes#count_down'
 patch 'wants/purchase' => 'wants#purchase'

# resources :users, :except => :show do
resources :users, only:[:index, :update, :edit, :achievement, :mypage, :follows, :followers, :hide, :search] do
  get :search, on: :collection
  resource :relationships, only: [:create, :destroy]
  get :follows
  get :followers
end


put 'users/:id/hide' => 'users#hide', as:'users_hide'
put 'wastes/:id/hide' => 'wastes#hide', as:'wastes_hide'
put 'wastes/:id/reveal' => 'wastes#reveal', as:'wastes_reveal'
put 'wastes/:id/hide_away' => 'wastes#hide_away', as:'wastes_hide_away'
put 'wants/:id/hide' => 'wants#hide', as:'wants_hide'
put 'wants/:id/reveal' => 'wants#reveal', as:'wants_reveal'

resources :wastes, only:[:index, :create, :count_up, :count_down, :update, :hide, :reveal, :hide_away]
resources :wants, only:[:index, :show, :create, :purchase, :update, :destroy, :hide, :reveal] do
  resource :cheers, only:[:create, :destroy]
end


root 'homes#top'
get 'homes/about'
get 'mypage' => 'users#mypage'
get 'achievement' => 'users#achievement'


end

app/models/waste.rb
class Waste < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: {maximum: 15}
  validates :price, numericality: { only_integer: true }
  validates :reason, length: {maximum: 15}
end

app/controllers/wastes_controller.rb
class WastesController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def index
    @user = current_user
    @waste = Waste.new
  end

  def create
    @waste = Waste.new(waste_params)
    @waste.user_id = current_user.id
    if @waste.save
      redirect_to wastes_path
    else
      @user = current_user
      render 'index'
    end
  end

  def count_up
    count_up_save

    # 〜〜部分テンプレート用〜〜
    @user = current_user
    @wastes = Waste.where(user_id: @user.id)
    calculation_waste_purchase
    # 現在の積みたて＝今使ってもいい額＝無駄遣い削減合計ー目標達成の購入額
    calculation_possible_total
  end

def count_down

  count_down_save
  # 〜〜部分テンプレート用〜〜
  @user = current_user
  @wastes = Waste.where(user_id: @user.id)
  calculation_waste_purchase
  # 現在の積みたて＝今使ってもいい額＝無駄遣い削減合計ー目標達成の購入額
  calculation_possible_total
end


def update
  @waste = Waste.find(params[:id])
  if @waste.update(waste_params)
    redirect_to wastes_path
  else
    @user = current_user
    render 'index'
  end
end

# ↓全体表示させるかさせないか削除してしまうか
def hide
  @waste = Waste.find(params[:id])
  @waste.update(status: 1)
  redirect_to wastes_path
end

def reveal
  @waste = Waste.find(params[:id])
  @waste.update(status: 0)
  redirect_to wastes_path
end

def hide_away
  @waste = Waste.find(params[:id])
  @waste.update(status: 2)
  flash[:hide] = "削除しました"
  redirect_to wastes_path
end



private
def waste_params
  params.require(:waste).permit(:name, :price, :reason)
end

end

app/helpers/wastes_helper.rb
module WastesHelper
end

app/views/wastes/_count.html.erb
<!-- 合計額計算している -->
<div class="row total-base">
  <div class="col-xs-6 saving">
    <h3>通算ガマン</h3>
    <h3><%= user_total_price.to_s(:delimited) %>円／<%= waste_count_all %>回</h3>
    <h3>現在の積立 (通算-購入額)</h3>
    <h3><%= user_difference_price.to_s(:delimited) %>円</h3>
  </div>
  <div class="col-xs-6 saving">
    <h3>みんなで積み上げた節約</h3>
    <h3><%= users_wastes_all.to_s(:delimited) %>円</h3>
    <h3>みんなの目標達成額</h3>
    <h3><%= users_purchase_all.to_s(:delimited) %>円</h3>
  </div>
</div>

<!-- 無駄遣い一覧表示、ボタンでcount up/down -->
<div class="row mytable">
  <div class="table-border table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>無駄遣い</th>
          <th>金額</th>
          <th>節約目的</th>
          <th>通算ガマン</th>
          <th>本日のガマン</th>
          <% if flash[:gain] %>
          <th class="notice">
            <%= flash[:gain] %>
          </th>
          <% elsif flash[:lose] %>
          <th class="alert">
            <%= flash[:lose] %>
          </th>
          <% else %>
          <th></th>
          <% end %>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% user.wastes.each do |waste| %>
        <% if waste.status == 0 %>
        <td><%= waste.name %></td>
        <td><%= waste.price.to_s(:delimited) %>円</td>
        <td><%= waste.reason %></td>
        <td><%= (waste.price * waste.count).to_s(:delimited) %>円／<%= waste.count %>回</td>
        <td><%= button_to "ガマン！", {controller: 'wastes', action: 'count_up'}, {method: :patch, :class => "btn btn-success", params: {waste: waste.id}, remote: true} %>
        </td>
        <td><%= button_to "使った…", {controller: 'wastes', action: 'count_down'}, {method: :patch, :class => "btn btn-danger", params: {waste: waste.id}, remote: true} %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

<div class="row index-btn">
  <%= link_to "無駄遣い変更/追加", wastes_path, class: "btn btn-default" %>
</div>

<div class="row mytable">
  <div class="table-border table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th class="col-xs-1">　　　　</th>
          <th class="col-xs-2">目標　　</th>
          <th class="col-xs-3">購入金額</th>
          <th class="col-xs-2">理由　　</th>
          <th class="col-xs-2">目標まで</th>
          <th class="col-xs-2">　　　　</th>
        </thead>
        <tbody>
          <tr>
            <% user.wants.each do |want| %>
            <td><%= want.cheers.count %><i class="fa fa-child" aria-hidden="true" style="color:red;"></i></td>
            <td><div class="resize">
              <%= attachment_image_tag want, :want_image, :fill, 45, 45, fallback: "want_no_image.jpg", size:'45x45' %><br><%= want.name %>
            </div></td>
            <td><%= want.price.to_s(:delimited) %>円</td>
            <td><%= want.reason %></td>
            <% if want.price-user_difference_price <= 0 %>
            <td><%= bar_chart [['積立金', user_difference_price], [want.name, want.price]], thousands: ",", width: "200px", height: "100px", colors: ["#4242ff", "#666"] %></td>
            <td><%= link_to want_path(want), class: "btn btn-primary" do %>
             積み立てた<br>お金で買う
             <% end %>
           </td>
           <% else %>
           <td><%= bar_chart [['積立金', user_difference_price], [want.name, want.price]], thousands: ",", width: "200px", height: "100px", colors: ["#ff5841", "#ffd1a3"] %></td>
           <td>あと<br><%= (want.price-user_difference_price).to_s(:delimited) %>円</td>
           <% end %>
         </tr>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>

app/views/wastes/count_down.js.erb
$('#count').html("<%= j(render partial: 'wastes/count', locals: { user_total_price: @user_total_price, user_difference_price: @user_difference_price, users_wastes_all: @users_wastes_all, users_purchase_all: @users_purchase_all, user: @user, waste_count_all: @waste_count_all }) %>");

app/views/wastes/count_up.js.erb
$('#count').html("<%= j(render partial: 'wastes/count', locals: { user_total_price: @user_total_price, user_difference_price: @user_difference_price, users_wastes_all: @users_wastes_all, users_purchase_all: @users_purchase_all, user: @user, waste_count_all: @waste_count_all }) %>");

app/views/wastes/index.html.erb
<div class="container">
  <div class="table-heading">
    <h2>無駄遣い一覧／変更</h2>
    <h4>(ガマンボタンや積み立ての確認はマイページ)</h4>
  </div>
  <div class="index-base">
    <div class="row">
      <!-- 無駄遣い一覧 -->
      <div class="table-border table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th class="col-xs-3">節約したいもの</th>
              <th class="col-xs-2">金額</th>
              <th class="col-xs-3">理由</th>
              <th class="col-xs-2">マイページに表示</th>

              <% if flash[:hide] %>
              <th class="col-xs-2 alert">
                <%= flash[:hide] %>
              </th>
              <% else %>
              <th class="col-xs-2">削除</th>
              <% end %>

            </tr>
          </thead>
          <tbody>
            <% @user.wastes.each do |waste| %>
            <% if waste.status != 2 %>
            <tr>
              <td><%= waste.name %></td>
              <td><%= waste.price.to_s(:delimited) %>円</td>
              <td><%= waste.reason %></td>
              <% if waste.status == 0 %>
              <td><%= link_to "マイページから隠す", wastes_hide_path(waste),method: :put, class: "btn btn-success"  %>
              </td>
              <td><%= link_to "無駄遣いから削除", wastes_hide_away_path(waste),method: :put, class: "btn btn-danger"  %></td>
              <% elsif waste.status == 1 %>
              <td><%= link_to "マイページに戻す", wastes_reveal_path(waste),method: :put, class: "btn btn-success"  %>
              </td>
              <td>
                <%= link_to "無駄遣いから削除", wastes_hide_away_path(waste),method: :put, class: "btn btn-danger"  %></td>
                <% else %>
                <td></td>
                <% end %>
                <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- 節約入力 -->
    <h2>節約したいものを入力</h2>
    <div class="index-base">
      <div class="row">
        <div class="table-border table-responsive">
          <%= form_with model: @waste,local: true do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <table class="table">
            <thead>
              <tr>
                <th class="col-xs-3">節約したいもの</th>
                <th class="col-xs-3">１個／1回あたりの値段(円)</th>
                <th class="col-xs-4">節約／辞めたい理由</th>
                <% if flash[:alert] %>
                <th class="col-xs-2 alert">
                  <%= flash[:alert] %>
                </th>
                <% else %>
                <th class="col-xs-2">更新</th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= f.text_field :name %></td>
                <td><%= f.text_field :price %></td>
                <td><%= f.text_field :reason %></td>
                <td><%= f.submit "追加", class: "btn btn-success" %></td>
              </tr>
            </tbody>
          </table>
          <% end %>
        </div>
      </div>
    </div>

    <!-- 遷移ボタン -->
    <div class="row row-btn">
      <div class="index-btn">
        <%= link_to "マイページ", mypage_path, class: "btn btn-default" %>
        <%= link_to "欲しいものを入力／変更する", wants_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>