config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, skip: [:password, :confirm], controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
  }

  # devise_for :users, skip: [:password, :confirm]


 patch 'wastes/count_up' => 'wastes#count_up'
 patch 'wastes/count_down' => 'wastes#count_down'
 patch 'wants/purchase' => 'wants#purchase'

# resources :users, :except => :show do
resources :users, only:[:index, :update, :edit, :achievement, :mypage, :follows, :followers, :hide, :search] do
  get :search, on: :collection
  resource :relationships, only: [:create, :destroy]
  get :follows
  get :followers
end


put 'users/:id/hide' => 'users#hide', as:'users_hide'
put 'wastes/:id/hide' => 'wastes#hide', as:'wastes_hide'
put 'wastes/:id/reveal' => 'wastes#reveal', as:'wastes_reveal'
put 'wastes/:id/hide_away' => 'wastes#hide_away', as:'wastes_hide_away'
put 'wants/:id/hide' => 'wants#hide', as:'wants_hide'
put 'wants/:id/reveal' => 'wants#reveal', as:'wants_reveal'

resources :wastes, only:[:index, :create, :count_up, :count_down, :update, :hide, :reveal, :hide_away]
resources :wants, only:[:index, :show, :create, :purchase, :update, :destroy, :hide, :reveal] do
  resource :cheers, only:[:create, :destroy]
end


root 'homes#top'
get 'homes/about'
get 'mypage' => 'users#mypage'
get 'achievement' => 'users#achievement'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wants
  has_many :wastes
  has_many :cheers, dependent: :destroy
  validates :nickname, presence: true, length: {maximum: 10}
  validates :email, presence: true
  validates :introduction, length: {maximum: 20}

  attachment :profile_image, content_type: ["image/jpeg", "image/png"]


  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  def active_for_authentication?
    super && (self.is_deleted == false )
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
   def new
    redirect_to new_user_session_path
     # super
   end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
 #  end

  def after_sign_up_path_for(resource)
    wants_path
  end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # before_action :reject_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user && (@user.valid_password?(params[:user][:password]) && (!@user.active_for_authentication?))
      flash[:alert] = "退会済みです。"
      render 'new'
    end
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end




  protected

  def reject_user
    @user = User.find_by(email: params[:user][:email].downcase)
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:alert] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:alert] = "必須項目を入力してください。"
    end
  end

  def after_sign_in_path_for(resource)
    mypage_path
  end
end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:update, :edit, :achievement, :mypage, :follows, :followers, :hide]
  include ApplicationHelper


  def index
  # ランダム表示
  if user_signed_in?
    @users = User.where(is_deleted: false).where.not(id: current_user.id).sample(7)
  else
    @users = User.where(is_deleted: false).sample(7)
  end
  @want = Want.new
end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path
    else
      @user = current_user
      @user.profile_image = current_user.profile_image
      render 'edit'
    end
  end

  def edit
    @user = current_user
  end

  def achievement
  end

  def mypage
    @user = current_user
    @wastes = Waste.where(user_id: @user.id)
    calculation_waste_purchase
    # 現在の積みたて＝今使ってもいい額＝無駄遣い削減合計ー目標達成の購入額
    calculation_possible_total
  end

  def follows
    @users = current_user.followings.where(is_deleted: false).page(params[:page]).per(5)
  end

  def followers
    @users = current_user.followers.where(is_deleted: false).page(params[:page]).per(5)
  end

  def hide # 退会オプション、destroyにしないのは合計額が崩れるから
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    # default = "f"
    reset_session
    flash[:thanks] = "買いたいものができたときのご利用お待ちしております"
    redirect_to root_path
  end

  def search # 検索用
    if params[:nickname].present?
      @users = User.where('nickname LIKE ?', "%#{params[:nickname]}%").page(params[:page]).per(5)
    else
      @users = User.none.page(params[:page]).per(5)
    end
  end

    private
    def user_params
      params.require(:user).permit(:nickname, :profile_image, :introduction, :email)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/views/users/_register.html.erb
<div class="container">

  <!-- 検索機能 -->
  <div class="row">
    <div class="col-xs-6">
    </div>
    <div class="index-btn">
      <div class="col-xs-6">
        <%= form_with url: search_users_path, method: :get, local: true do |f| %>
        <%= f.text_field :nickname, placeholder: "ユーザー名" %>
        <%= f.submit "ユーザーを検索" %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- 検索機能 -->

  <!-- ユーザの一覧表示 -->
  <% @users.each do |user| %>
  <!-- 退会していない人＝有効のみ表示 -->
  <% if user.is_deleted == false %>
  <div class="table-base">
    <div class="row">
      <div class="table-border table-responsive">
        <table class="table">
          <thead>
            <% if @user != current_user %>
            <tr valign="middle">
              <th class="col-xs-3">ユーザー</th>
              <th class="col-xs-3">通算節約金額</th>
              <th class="col-xs-4">意気込み</th>
              <th class="col-xs-2">フォロー</th>
            </tr>
            <% else %>
            <tr valign="middle">
              <th class="col-xs-4">ユーザー</th>
              <th class="col-xs-4">通算節約金額</th>
              <th class="col-xs-4">意気込み</th>
            </tr>
            <% end %>
          </thead>
          <tbody>
            <tr valign="middle">
              <td>
                <div class="resize"><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %><br><%= user.nickname %></div></td>
              <td><% sum = 0 %>
                  <% user.wastes.each do |waste| %>
                  <% sub_total = waste.price * waste.count %>
                  <% sum+=sub_total %>
                  <% end %>
                  <%= sum.to_s(:delimited) %>円
                  <% if user_signed_in? %></td>
              <td><%= user.introduction %></td>
              <td>
                <div id="follows_buttons_<%= user.id %>">
                    <%= render partial: 'relationships/follow', locals:{ user: user } %>
                </div></td>
                  <% else %>
              <td></td>
                  <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- 欲しいもののテーブル -->
    <div class="row">
      <div class="table-border table-responsive">
        <table class="table">
          <thead>
            <% if @user != current_user %>
            <tr>
              <th class="col-xs-3">欲しいもの</th>
              <th class="col-xs-3">金額</th>
              <th class="col-xs-4">欲しい理由</th>
              <th class="col-xs-2">応援！</th>
            </tr>
            <% else %>
            <tr>
              <th class="col-xs-4">欲しいもの</th>
              <th class="col-xs-4">金額</th>
              <th class="col-xs-4">欲しい理由</th>
            </tr>
            <% end %>
          </thead>
          <tbody class="window_btn">
            <% user.wants.each_with_index do |want, i| %>
            <% if want.status == 0 %>
            <tr>
              <td><div class="resize"><%= attachment_image_tag want, :want_image, :fill, 45, 45, fallback: "want_no_image.jpg" %><br><%= want.name %></div></td>
              <td><%= want.price.to_s(:delimited) %>円</td>
              <td><%= want.reason %></td>
              <% if @user != current_user %>
              <td>
                <div id="cheers_buttons_<%= want.id %>">
                  <%= render partial: 'wants/cheer', locals:{ want: want } %>
                </div>
                <div id="btn_<%= user.id %>_<%= i %>", class="contents">
                  <%= form_with model: want, method: :post, url: wants_path, remote: true do |f| %>
                  <%= f.hidden_field :want_image_id, value: want.want_image_id %>
                  <%= f.hidden_field :name, value: want.name %>
                  <%= f.hidden_field :price, value: want.price %>
                  <%= f.hidden_field :row_number, value: "#{user.id}_#{i}" %>
                  <%= f.submit "私も欲しい！", class: "btn btn-default" %>
                  <% end %>
                </div>
              </td>
              <% end %>
            </tr>
            <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  <!-- 無駄遣いのテーブル -->
    <div class="row">
      <div class="table-border table-responsive">
        <table class="table">
        <thead>
          <% if @user != current_user %>
          <tr>
            <th class="col-xs-3">無駄遣い</th>
            <th class="col-xs-3">金額</th>
            <th class="col-xs-4">無駄に思っている理由</th>
            <th class="col-xs-2"></th>
          </tr>
          <% else %>
          <tr>
            <th class="col-xs-4">無駄遣い</th>
            <th class="col-xs-4">金額</th>
            <th class="col-xs-4">無駄に思っている理由</th>
          </tr>
          <% end %>
        </thead>
          <tbody>
            <% user.wastes.each do |waste| %>
              <% if waste.status == 0 %>
                <% if @user != current_user %>
            <tr>
              <td><%= waste.name %></td>
              <td><%= waste.price.to_s(:delimited) %>円</td>
              <td><%= waste.reason %></td>
              <td></td>
            </tr>
                <% else %>
            <tr>
              <td><%= waste.name %></td>
              <td><%= waste.price.to_s(:delimited) %>円</td>
              <td><%= waste.reason %></td>
            </tr>
                <% end %>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>
<% end %>


  <% if request.path.include?("follows" || "followers") %>
    <div class="row pagination-btn">
      <div>
        <%= paginate @users %>
      </div>
    </div>
  <% else %>
  <% end %>

</div>

app/views/users/achievement.html.erb
<!-- 目標達成画面 -->
<div class="container">
  <div class="achievement-base">
    <div class="row">
      目標達成！<br>おめでとうございます！
    </div>
  </div>

  <div class="row">
    <div class="index-btn">
      <%= link_to "マイページ", mypage_path, class: "btn btn-default" %>
      <%= link_to "目標を追加／変更する", wants_path ,class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= form_for @user do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-signin">
    <div class="user-info">
      <h2>プロフィールの変更</h2>
      <div class="field">
        <label>プロフィール画像</label><br>
        <%= f.file_field :profile_image, class: "img_field", style: "display:none;", accept: 'image/jpg, image/jpeg, image/png' %>
        <%= attachment_image_tag @user, :profile_image, placeholder: "プロフィール画像", fallback: "no_image.jpg", size:'90x90', onClick: "$('.img_field').click()", class: "center-block img-thumbnail img-responsive img_prev" %>
      </div>
      <div class="field">
        <%= f.label :ニックネーム %><br />
        <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" %>
      </div>

      <div class="field">
        <%= f.label :メールアドレス %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="field">
        <%= f.label :意気込み %><br />
        <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" %>
      </div>

      <div class="actions">
        <%= f.submit "プロフィールの更新", class: "btn btn-success"  %>
      </div>
      <%#= link_to "パスワードお忘れですか？", new_password_path(resource_name) %><br />
      <div class="actions">
        <% if user_signed_in? && @user.id == current_user.id %>
        <%= link_to "退会する", users_hide_path(current_user), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="container">
  <h2>フォロワー一覧</h2>
</div>
<%= render "users/register" %>

app/views/users/follows.html.erb
<div class="container">
  <h2>フォロー一覧</h2>
</div>
<%= render "users/register" %>

app/views/users/index.html.erb
<!-- ユーザー一覧表示、ログイン前後どう表示させるかはregister内で条件分けしている -->
<div class="container">
  <div class="row">
    <div class="table-heading">
      <h2>ユーザー一覧</h2><h4>ランダムで7件表示</h4>
    </div>
  </div>
</div>
<%= render "users/register" %>
<div class="container">
  <div class="row random">
    <div>
      <%= link_to "他のユーザーも確認する", users_path, class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/users/mypage.html.erb
<div class="container">
  <div class="profile">
    <div class="row align-middle">
      <!-- プロフィールの名前と画像表示 -->
      <div class="col-xs-3">
        <div class="profile-image">
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle", fallback: "no_image.jpg", size:'100x100' %><br>
        </div>
        <p><%= current_user.nickname %></p>
      </div>
      <div class="col-xs-4">
        <div class="intro">
          <p><%= current_user.introduction %></p>
        </div>
      </div>
      <!-- プロフィールのフォロー表示 -->
      <div class="col-xs-5">
        <div class="follow">
          <div>
            <a><%= link_to user_follows_path(current_user.id) do %>
              <%= @user.followings.count %><br>
              フォロー
              <% end %></a>
              <a><%= link_to user_followers_path(current_user.id) do %>
                <%= @user.followers.count %><br>
                フォロワー
                <% end %></a>
              </div>
              <div>
               <%= link_to "プロフィール変更", edit_user_path(current_user) %>
             </div>
           </div>
         </div>
       </div>
     </div>

     <!-- 無駄遣いを管理するテーブル、ボタンと合計額、グラフを表示する部分テンプレート -->
     <div id="count">
      <%= render partial: 'wastes/count', locals: { user_total_price: @user_total_price, user_difference_price: @user_difference_price, users_wastes_all: @users_wastes_all, users_purchase_all: @users_purchase_all, user: @user,waste_count_all: @waste_count_all } %>
    </div>

    <!-- 遷移ボタン -->
    <div class="row index-btn">
      <%= link_to "目標変更", wants_path, class: "btn btn-default" %>
    </div>
  </div>

app/views/users/search.html.erb
<!-- 検索結果一覧表示 -->
<div class="container">
  <div class="row">
    <h2>検索結果</h2>
<!-- ユーザー一覧表示させる -->
    <%= render "users/register" %>
  </div>
</div>