config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, skip: [:password, :confirm], controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
  }

  # devise_for :users, skip: [:password, :confirm]


 patch 'wastes/count_up' => 'wastes#count_up'
 patch 'wastes/count_down' => 'wastes#count_down'
 patch 'wants/purchase' => 'wants#purchase'

# resources :users, :except => :show do
resources :users, only:[:index, :update, :edit, :achievement, :mypage, :follows, :followers, :hide, :search] do
  get :search, on: :collection
  resource :relationships, only: [:create, :destroy]
  get :follows
  get :followers
end


put 'users/:id/hide' => 'users#hide', as:'users_hide'
put 'wastes/:id/hide' => 'wastes#hide', as:'wastes_hide'
put 'wastes/:id/reveal' => 'wastes#reveal', as:'wastes_reveal'
put 'wastes/:id/hide_away' => 'wastes#hide_away', as:'wastes_hide_away'
put 'wants/:id/hide' => 'wants#hide', as:'wants_hide'
put 'wants/:id/reveal' => 'wants#reveal', as:'wants_reveal'

resources :wastes, only:[:index, :create, :count_up, :count_down, :update, :hide, :reveal, :hide_away]
resources :wants, only:[:index, :show, :create, :purchase, :update, :destroy, :hide, :reveal] do
  resource :cheers, only:[:create, :destroy]
end


root 'homes#top'
get 'homes/about'
get 'mypage' => 'users#mypage'
get 'achievement' => 'users#achievement'


end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id=“error_messages” class="error_style">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
        <% if flash[:file_error] %>
      <li>
        <%= flash[:file_error] %>
      </li>
       <% end %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_share_btn.html.erb
<div class="share_btn">

  <p>目標をシェアする</p>
  <div class="fb-share-button" data-href="https://cotsutsumi.work" data-layout="button" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fcotsutsumi.work%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">シェア</a>
  </div>

  <div class="twitter">
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="欲しいものを買うまでこつつみで支出管理！" data-url="https://cotsutsumi.work" data-lang="ja" data-hashtags="こつつみ" >Tweet</a>
   </div>

  <div class="line-it-button" data-lang="ja" data-type="share-a" data-ver="3" data-url="https://cotsutsumi.work" data-color="default" data-size="small" data-count="false" style="display: none;">
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>こつつみ</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <meta name="turbolinks-cache-control" content="no-cache">
  <%= display_meta_tags(default_meta_tags) %>
</head>

<body>
  <div id="wrapper">
    <!-- /header -->
    <div class="head-group">
      <header>
        <div class="container">
          <div class="row">
            <nav  class="nav navbar-nav navbar-left">
              <div class="logo">
                <%= link_to root_path do %>
                <%= image_tag('1_Primary_logo_on_transparent_301x67.png') %>

                <% end %>
              </div>
            </nav>
            <nav class="nav navbar-nav navbar-right">
              <li><%= link_to "About", homes_about_path, class: "btn btn-default" %></li>
                <% if request.path.include?("sign_in" || "sign_up") || !user_signed_in? %>
              <li><%= link_to "ユーザー一覧", users_path, class: "btn btn-default" %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: "btn btn-default" %></li>
              <li><%= link_to "ログイン", new_user_session_path, class: "btn btn-default" %></li>
                <% else %>
              <li><%= link_to "マイページ", mypage_path, class: "btn btn-default" %></li>
              <li><%= link_to "ユーザー一覧", users_path, class: "btn btn-default" %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-default" %></li>
                <% end %>
            </nav>
          </div>
        </div>
      </header>
      <!-- シェア用アイコン -->
      <div class="container">
        <div class="row">
          <div id="fb-root"></div>
          <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v8.0" nonce="cnjnh5d7"></script>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <script src="https://d.line-scdn.net/r/web/social-plugin/js/thirdparty/loader.min.js" async="async" defer="defer"></script>
          <%= render "layouts/share_btn" %>
        </div>
      </div>
    </div>
    <!-- シェア用アイコン -->
    <!-- /header -->

    <% if flash[:thanks] %>
      <div class="container">
        <div class="row">
          <div class="thanks top-base">
            <%= flash[:thanks] %>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>

    <footer>
      <div>
        <p>CopyRight Cotsutsumi</p>
      </div>
    </footer>
  </div>
</body>
</html>